### ISSUE TITLE
Tried using unknown condition table called sculk:has_healthbar

### ISSUE THREAD

**Issue by htcham** [finalsingularity/the-otherside#1]
Playing on 1.20.1 vanilla java server, the console is being _flooded_ with the text _"Tried using unknown condition table called sculk:has_healthbar"_
It's not crashing the server, but I believe it's impacting performance

**Comment by moxvallix** [comment]
The pack hasn't been updated to 1.20 yet. Predicate format has changed, so I will need to update the predicates in the pack before it will work.
